create schema if not exists analytics;

create table if not exists analytics.analytics_events (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default now(),
  event text not null,
  install_id text not null,
  session_id text not null,
  app_version text,
  os text,
  props jsonb not null default '{}'::jsonb,
  schema_version integer not null default 1
);

create index if not exists analytics_events_received_at_idx
  on analytics.analytics_events (received_at desc);
create index if not exists analytics_events_event_idx
  on analytics.analytics_events (event);
create index if not exists analytics_events_app_version_idx
  on analytics.analytics_events (app_version);
create index if not exists analytics_events_props_gin_idx
  on analytics.analytics_events using gin (props);

create table if not exists analytics.analytics_daily (
  day date not null,
  event text not null,
  app_version text not null default '',
  count bigint not null default 0,
  primary key (day, event, app_version)
);

alter table analytics.analytics_events enable row level security;
alter table analytics.analytics_daily enable row level security;

create or replace function analytics.rollup_analytics_event()
returns trigger
language plpgsql
security definer
set search_path = analytics, pg_temp
as $$
begin
  insert into analytics.analytics_daily (day, event, app_version, count)
  values (new.received_at::date, new.event, coalesce(new.app_version, ''), 1)
  on conflict (day, event, app_version)
  do update set count = analytics.analytics_daily.count + 1;
  return new;
end;
$$;

drop trigger if exists analytics_events_daily_rollup on analytics.analytics_events;
create trigger analytics_events_daily_rollup
after insert on analytics.analytics_events
for each row execute function analytics.rollup_analytics_event();
